name = "wordle-tamil-words-api"
main = "src/index.js"
compatibility_date = "2024-11-01"

# Created via: wrangler d1 create wordle-tamil-words
# Then paste the returned database_id below.
[[d1_databases]]
binding = "DB"
database_name = "wordle-tamil-words"
database_id = "9d7d95fd-7a8a-4c80-8018-8cb8046c9772"
